"""baseline schema

Revision ID: 7bc509b72116
Revises: 
Create Date: 2026-08-27 16:51:53.690289

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7bc509b72116'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('comparator', sa.String(length=4), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=True),
    sa.Column('horizon_filter', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('station_slug', sa.String(length=80), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('observed_or_forecast', sa.String(length=12), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_triggered', 'alerts', ['triggered_at'], unique=False)
    op.create_table('data_quality_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_slug', sa.String(length=80), nullable=True),
    sa.Column('check_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dq_detected', 'data_quality_logs', ['detected_at'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('requires_key', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('row_counts_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=48), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('train_start', sa.DateTime(), nullable=True),
    sa.Column('train_end', sa.DateTime(), nullable=True),
    sa.Column('val_scheme', sa.String(length=48), nullable=True),
    sa.Column('dataset_hash', sa.String(length=64), nullable=True),
    sa.Column('git_sha', sa.String(length=48), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('artifact_uri', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_slug')
    )
    op.create_index(op.f('ix_stations_city'), 'stations', ['city'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_slug', sa.String(length=80), nullable=False),
    sa.Column('feature_time', sa.DateTime(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('feature_set_version', sa.String(length=48), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_slug'], ['stations.canonical_slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_slug', 'feature_time', 'horizon_hours', 'feature_set_version', name='uq_feature_row')
    )
    op.create_index('ix_feat_station_time', 'features', ['station_slug', 'feature_set_version', 'feature_time'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_slug', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=12), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('target_time', sa.DateTime(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=True),
    sa.Column('p10', sa.Float(), nullable=True),
    sa.Column('p90', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=12), nullable=True),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('feature_set_version', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['station_slug'], ['stations.canonical_slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_slug', 'target', 'issued_at', 'horizon_hours', name='uq_forecast')
    )
    op.create_index('ix_fc_station_target_time', 'forecasts', ['station_slug', 'target', 'target_time'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('station_slug', sa.String(length=80), nullable=True),
    sa.Column('season', sa.String(length=16), nullable=True),
    sa.Column('target', sa.String(length=12), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('smape', sa.Float(), nullable=True),
    sa.Column('picp_80', sa.Float(), nullable=True),
    sa.Column('pinaw_80', sa.Float(), nullable=True),
    sa.Column('winkler_80', sa.Float(), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_lookup', 'model_metrics', ['target', 'horizon_hours', 'scope'], unique=False)
    op.create_table('pollution_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_slug', sa.String(length=80), nullable=False),
    sa.Column('pollutant', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('quality_flag', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_pollution_nonnegative'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_slug'], ['stations.canonical_slug'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_slug', 'pollutant', 'observed_at', 'source_id', name='uq_pollution_obs')
    )
    op.create_index('ix_pol_station_time', 'pollution_observations', ['station_slug', 'pollutant', 'observed_at'], unique=False)
    op.create_table('station_name_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('canonical_slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_slug'], ['stations.canonical_slug'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'provider_name', name='uq_provider_alias')
    )
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_slug', sa.String(length=80), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('relative_humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('wind_gust_ms', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('quality_flag', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('precipitation_mm IS NULL OR precipitation_mm >= 0', name='ck_precip_nonneg'),
    sa.CheckConstraint('relative_humidity_pct IS NULL OR (relative_humidity_pct BETWEEN 0 AND 100)', name='ck_rh_range'),
    sa.CheckConstraint('wind_speed_ms IS NULL OR wind_speed_ms >= 0', name='ck_ws_nonnegative'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_slug'], ['stations.canonical_slug'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_slug', 'observed_at', 'source_id', name='uq_weather_obs')
    )
    op.create_index('ix_wx_station_time', 'weather_observations', ['station_slug', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wx_station_time', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_table('station_name_aliases')
    op.drop_index('ix_pol_station_time', table_name='pollution_observations')
    op.drop_table('pollution_observations')
    op.drop_index('ix_metric_lookup', table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index('ix_fc_station_target_time', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_feat_station_time', table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_stations_city'), table_name='stations')
    op.drop_table('stations')
    op.drop_table('model_runs')
    op.drop_table('dataset_versions')
    op.drop_table('data_sources')
    op.drop_index('ix_dq_detected', table_name='data_quality_logs')
    op.drop_table('data_quality_logs')
    op.drop_index('ix_alert_triggered', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
