"""Canonical NCR station catalog.

Auto-generated from frontend/src/lib/demo/data.ts STATION_DEFS so backend
slugs match what the dashboard already consumes. Regenerate instead of
hand-editing when the frontend list changes.
"""

STATION_CATALOG: list[dict] = [
    {
        "slug": "anand-vihar",
        "name": "Anand Vihar",
        "city": "Delhi",
        "latitude": 28.6469,
        "longitude": 77.3162,
    },
    {
        "slug": "ashok-vihar",
        "name": "Ashok Vihar",
        "city": "Delhi",
        "latitude": 28.6954,
        "longitude": 77.1817,
    },
    {
        "slug": "aya-nagar",
        "name": "Aya Nagar",
        "city": "Delhi",
        "latitude": 28.4706,
        "longitude": 77.1099,
    },
    {
        "slug": "bawana",
        "name": "Bawana",
        "city": "Delhi",
        "latitude": 28.7762,
        "longitude": 77.0512,
    },
    {
        "slug": "burari-crossing",
        "name": "Burari Crossing",
        "city": "Delhi",
        "latitude": 28.7256,
        "longitude": 77.2011,
    },
    {
        "slug": "crri-mathura-road",
        "name": "CRRI Mathura Road",
        "city": "Delhi",
        "latitude": 28.5512,
        "longitude": 77.2735,
    },
    {
        "slug": "chandni-chowk",
        "name": "Chandni Chowk",
        "city": "Delhi",
        "latitude": 28.6562,
        "longitude": 77.23,
    },
    {"slug": "dtu", "name": "DTU", "city": "Delhi", "latitude": 28.75, "longitude": 77.1112},
    {
        "slug": "karni-singh-range",
        "name": "Dr. Karni Singh Shooting Range",
        "city": "Delhi",
        "latitude": 28.4986,
        "longitude": 77.2648,
    },
    {
        "slug": "dwarka-sector-8",
        "name": "Dwarka Sector 8",
        "city": "Delhi",
        "latitude": 28.571,
        "longitude": 77.0719,
    },
    {
        "slug": "igi-airport-t3",
        "name": "IGI Airport T3",
        "city": "Delhi",
        "latitude": 28.5628,
        "longitude": 77.118,
    },
    {
        "slug": "ihbas-dilshad-garden",
        "name": "IHBAS Dilshad Garden",
        "city": "Delhi",
        "latitude": 28.6811,
        "longitude": 77.3025,
    },
    {"slug": "ito", "name": "ITO", "city": "Delhi", "latitude": 28.6285, "longitude": 77.241},
    {
        "slug": "jahangirpuri",
        "name": "Jahangirpuri",
        "city": "Delhi",
        "latitude": 28.7328,
        "longitude": 77.1707,
    },
    {
        "slug": "jn-stadium",
        "name": "Jawaharlal Nehru Stadium",
        "city": "Delhi",
        "latitude": 28.58,
        "longitude": 77.2337,
    },
    {
        "slug": "lodhi-road",
        "name": "Lodhi Road",
        "city": "Delhi",
        "latitude": 28.5918,
        "longitude": 77.2273,
    },
    {
        "slug": "dhyan-chand-stadium",
        "name": "Major Dhyan Chand Stadium",
        "city": "Delhi",
        "latitude": 28.6129,
        "longitude": 77.2373,
    },
    {
        "slug": "mandir-marg",
        "name": "Mandir Marg",
        "city": "Delhi",
        "latitude": 28.6365,
        "longitude": 77.2011,
    },
    {
        "slug": "mundka",
        "name": "Mundka",
        "city": "Delhi",
        "latitude": 28.6825,
        "longitude": 77.0768,
    },
    {
        "slug": "najafgarh",
        "name": "Najafgarh",
        "city": "Delhi",
        "latitude": 28.57,
        "longitude": 76.9337,
    },
    {
        "slug": "narela",
        "name": "Narela",
        "city": "Delhi",
        "latitude": 28.8227,
        "longitude": 77.1018,
    },
    {
        "slug": "nehru-nagar",
        "name": "Nehru Nagar",
        "city": "Delhi",
        "latitude": 28.5677,
        "longitude": 77.2508,
    },
    {
        "slug": "new-moti-bagh",
        "name": "New Moti Bagh",
        "city": "Delhi",
        "latitude": 28.5718,
        "longitude": 77.183,
    },
    {
        "slug": "north-campus-du",
        "name": "North Campus DU",
        "city": "Delhi",
        "latitude": 28.6573,
        "longitude": 77.1585,
    },
    {
        "slug": "nsit-dwarka",
        "name": "NSIT Dwarka",
        "city": "Delhi",
        "latitude": 28.609,
        "longitude": 77.0325,
    },
    {
        "slug": "okhla-phase-2",
        "name": "Okhla Phase-2",
        "city": "Delhi",
        "latitude": 28.5307,
        "longitude": 77.2712,
    },
    {
        "slug": "patparganj",
        "name": "Patparganj",
        "city": "Delhi",
        "latitude": 28.6236,
        "longitude": 77.2872,
    },
    {
        "slug": "punjabi-bagh",
        "name": "Punjabi Bagh",
        "city": "Delhi",
        "latitude": 28.674,
        "longitude": 77.131,
    },
    {"slug": "pusa", "name": "Pusa", "city": "Delhi", "latitude": 28.6398, "longitude": 77.1462},
    {
        "slug": "rk-puram",
        "name": "R K Puram",
        "city": "Delhi",
        "latitude": 28.5646,
        "longitude": 77.167,
    },
    {
        "slug": "rohini",
        "name": "Rohini",
        "city": "Delhi",
        "latitude": 28.7325,
        "longitude": 77.1198,
    },
    {
        "slug": "shadipur",
        "name": "Shadipur",
        "city": "Delhi",
        "latitude": 28.6514,
        "longitude": 77.1473,
    },
    {
        "slug": "sirifort",
        "name": "Sirifort",
        "city": "Delhi",
        "latitude": 28.5504,
        "longitude": 77.2159,
    },
    {
        "slug": "sonia-vihar",
        "name": "Sonia Vihar",
        "city": "Delhi",
        "latitude": 28.7106,
        "longitude": 77.2497,
    },
    {
        "slug": "sri-aurobindo-marg",
        "name": "Sri Aurobindo Marg",
        "city": "Delhi",
        "latitude": 28.5312,
        "longitude": 77.1904,
    },
    {
        "slug": "vivek-vihar",
        "name": "Vivek Vihar",
        "city": "Delhi",
        "latitude": 28.6725,
        "longitude": 77.3153,
    },
    {
        "slug": "wazirpur",
        "name": "Wazirpur",
        "city": "Delhi",
        "latitude": 28.6997,
        "longitude": 77.1653,
    },
    {
        "slug": "noida-sector-116",
        "name": "Noida Sector 116",
        "city": "Noida",
        "latitude": 28.5833,
        "longitude": 77.34,
    },
    {
        "slug": "noida-sector-125",
        "name": "Noida Sector 125",
        "city": "Noida",
        "latitude": 28.545,
        "longitude": 77.333,
    },
    {
        "slug": "noida-sector-1",
        "name": "Noida Sector 1",
        "city": "Noida",
        "latitude": 28.571,
        "longitude": 77.326,
    },
    {
        "slug": "knowledge-park-v",
        "name": "Knowledge Park V",
        "city": "Greater Noida",
        "latitude": 28.475,
        "longitude": 77.503,
    },
    {
        "slug": "indirapuram",
        "name": "Indirapuram",
        "city": "Ghaziabad",
        "latitude": 28.646,
        "longitude": 77.356,
    },
    {"slug": "loni", "name": "Loni", "city": "Ghaziabad", "latitude": 28.751, "longitude": 77.271},
    {
        "slug": "sanjay-nagar",
        "name": "Sanjay Nagar",
        "city": "Ghaziabad",
        "latitude": 28.672,
        "longitude": 77.42,
    },
    {
        "slug": "vasundhara",
        "name": "Vasundhara",
        "city": "Ghaziabad",
        "latitude": 28.66,
        "longitude": 77.372,
    },
    {
        "slug": "gwal-pahari",
        "name": "Gwal Pahari",
        "city": "Gurugram",
        "latitude": 28.394,
        "longitude": 77.156,
    },
    {
        "slug": "gurugram-sector-51",
        "name": "Gurugram Sector 51",
        "city": "Gurugram",
        "latitude": 28.42,
        "longitude": 77.065,
    },
    {
        "slug": "vikas-sadan",
        "name": "Vikas Sadan",
        "city": "Gurugram",
        "latitude": 28.459,
        "longitude": 77.023,
    },
    {
        "slug": "teri-gram",
        "name": "Teri Gram",
        "city": "Gurugram",
        "latitude": 28.409,
        "longitude": 77.15,
    },
    {
        "slug": "faridabad-sector-11",
        "name": "Faridabad Sector 11",
        "city": "Faridabad",
        "latitude": 28.365,
        "longitude": 77.316,
    },
    {
        "slug": "faridabad-sector-16a",
        "name": "Faridabad Sector 16A",
        "city": "Faridabad",
        "latitude": 28.334,
        "longitude": 77.291,
    },
    {
        "slug": "nit-faridabad",
        "name": "NIT Faridabad",
        "city": "Faridabad",
        "latitude": 28.313,
        "longitude": 77.287,
    },
    {
        "slug": "bahadurgarh",
        "name": "Bahadurgarh",
        "city": "Other NCR",
        "latitude": 28.693,
        "longitude": 76.938,
    },
    {
        "slug": "ballabgarh",
        "name": "Ballabgarh",
        "city": "Other NCR",
        "latitude": 28.339,
        "longitude": 77.305,
    },
]
